#!/usr/bin/env bash
# Generate a ready-to-run .env, an htpasswd file (when BASIC_AUTH=1), and a
# self-signed TLS cert (when TLS=1). All secrets land in ./secrets/ with
# mode 0600; the .env file holds only the path references.
#
# By default the app is open: no auth, no TLS — front it with your own
# reverse proxy if you need either. Set BASIC_AUTH=1 and/or TLS=1 in
# .env.example (or pass them via the environment) to opt in.
#
# Usage:
#   ./scripts/init-env.sh               # interactive defaults (open + plain)
#   BASIC_AUTH=1 TLS=1 ./scripts/init-env.sh
#   ./scripts/init-env.sh --force       # overwrite .env and secrets/
#
# Requires: openssl. htpasswd is optional — when missing we generate the
# entry via openssl's passwd -apr1 (Apache MD5).

set -euo pipefail
cd "$(dirname "$0")/.."

force=0
for a in "$@"; do
  case "$a" in
    --force|-f) force=1 ;;
    -h|--help)
      sed -n '2,25p' "$0"
      exit 0
      ;;
  esac
done

if [ -f .env ] && [ "$force" -ne 1 ]; then
  echo ".env already exists — refusing to overwrite. Re-run with --force to regenerate."
  exit 0
fi
if [ -d secrets ] && [ "$force" -ne 1 ]; then
  echo "secrets/ already exists — refusing to overwrite. Re-run with --force to regenerate."
  exit 0
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl is required to generate secrets." >&2
  exit 1
fi

mkdir -p secrets
chmod 700 secrets

# ---- .env --------------------------------------------------------------------
# Pull user-overridable values from the existing environment (so callers
# can run `BASIC_AUTH=1 TLS=1 ./scripts/init-env.sh`).
WEB_PORT="${WEB_PORT:-8080}"
TLS_PORT="${TLS_PORT:-8443}"
SANDBOX_RUNNER_PORT="${SANDBOX_RUNNER_PORT:-8090}"
BASIC_AUTH="${BASIC_AUTH:-0}"
TLS="${TLS:-0}"

cat > .env <<INNER
# Generated by scripts/init-env.sh — keep this file secret.
# Re-running with --force wipes .env AND secrets/.

POSTGRES_USER=detonate
POSTGRES_DB=detonate
# Postgres password is mounted as a compose secret (db_password), not an
# env var. The api container reads DB_PASSWORD_FILE=/run/secrets/db_password.

WEB_PORT=${WEB_PORT}
TLS_PORT=${TLS_PORT}
SANDBOX_RUNNER_PORT=${SANDBOX_RUNNER_PORT}

# Analysis engine.
#   static     — extract strings from the file and match signatures.
#   simulated  — fabricate a report from the hash (demo only).
#   docker     — run the sample in a real sandbox (requires the sandbox
#                profile: 'make up-sandbox').
SANDBOX_CONNECTOR=static
RETAIN_BYTES=true
MAX_UPLOAD_BYTES=104857600
ANALYSIS_CONCURRENCY=2

RATE_MAX_REQUESTS=120
SUBMIT_MAX_REQUESTS=12

# Optional HTTP BasicAuth at the web tier (0 or 1). When 1, the web
# container will require an Authorization: Basic ... header against the
# credentials in secrets/web_basic_auth_htpasswd.
BASIC_AUTH=${BASIC_AUTH}

# Optional self-signed TLS at the web tier (0 or 1). When 1, nginx
# listens on TLS_PORT inside the web container and uses the cert+key in
# secrets/web_tls_*.pem.
TLS=${TLS}
INNER

chmod 600 .env

# ---- secrets/db_password ----------------------------------------------------
openssl rand -hex 24 > secrets/db_password
chmod 600 secrets/db_password

# ---- secrets/sandbox_runner_token ------------------------------------------
# The api container signs each detonation request with this token; the
# sandbox-runner container verifies it. 32 bytes hex = 64 chars.
openssl rand -hex 32 > secrets/sandbox_runner_token
chmod 600 secrets/sandbox_runner_token

# ---- secrets/web_basic_auth_htpasswd (only if BASIC_AUTH=1) -----------------
if [ "$BASIC_AUTH" = "1" ]; then
  user="detonate"
  pass=$(openssl rand -base64 18 | tr -d '+/=' | head -c 22)
  if command -v htpasswd >/dev/null 2>&1; then
    htpasswd -cb secrets/web_basic_auth_htpasswd "$user" "$pass"
  else
    # Fall back to openssl's passwd -apr1 (Apache MD5). nginx accepts
    # both the crypt(3) and the APR1 variants.
    hashed=$(openssl passwd -apr1 "$pass")
    printf '%s:%s\n' "$user" "$hashed" > secrets/web_basic_auth_htpasswd
  fi
  chmod 600 secrets/web_basic_auth_htpasswd
  printf '\n# ---- BasicAuth credentials (write these down; we won'\''t show them again) ----\n'
  printf 'user:     %s\n' "$user"
  printf 'password: %s\n' "$pass"
fi

# ---- secrets/web_tls_*.pem (only if TLS=1) ----------------------------------
if [ "$TLS" = "1" ]; then
  openssl req -x509 -newkey rsa:2048 -days 365 -nodes \
    -keyout secrets/web_tls_key.pem \
    -out    secrets/web_tls_cert.pem \
    -subj "/CN=localhost" \
    -addext "subjectAltName=DNS:localhost,IP:127.0.0.1" 2>/dev/null
  chmod 600 secrets/web_tls_key.pem
  chmod 644 secrets/web_tls_cert.pem
  printf '\n# ---- TLS cert (self-signed, 1 year) -----------------------------------\n'
  printf 'cert: secrets/web_tls_cert.pem\nkey:  secrets/web_tls_key.pem\n'
fi

cat <<'NEXT'

Done.
  secrets/  contains the live secrets (chmod 600).
  .env      contains only the path references (chmod 600).

Next:  make apparmor-load    (if your kernel has AppArmor)
        make up
        open http://localhost:${WEB_PORT}
NEXT

if [ "$BASIC_AUTH" = "1" ]; then
  echo "BasicAuth is ENABLED — credentials printed above."
fi
if [ "$TLS" = "1" ]; then
  echo "TLS is ENABLED — self-signed cert in secrets/ (browsers will warn)."
fi