#!/usr/bin/env bash
# Generate a ready-to-run .env with strong random secrets and a bootstrap admin.
set -euo pipefail
cd "$(dirname "$0")/.."

if [ -f .env ]; then
  echo ".env already exists — refusing to overwrite. Delete it first to regenerate."
  exit 0
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl is required to generate secrets." >&2
  exit 1
fi

ADMIN_EMAIL="${1:-admin@detonate.io}"
ADMIN_PASS="$(openssl rand -base64 24 | tr -dc 'A-Za-z0-9' | cut -c1-20)"

cat > .env <<EOF
# Generated by scripts/init-env.sh — keep this file secret.
POSTGRES_USER=detonate
POSTGRES_PASSWORD=$(openssl rand -hex 24)
POSTGRES_DB=detonate

DL_ENVIRONMENT=production
DL_SECRET_KEY=$(openssl rand -hex 32)
DL_ALLOW_REGISTRATION=true
DL_COOKIE_SECURE=false

DL_ADMIN_EMAIL=${ADMIN_EMAIL}
DL_ADMIN_PASSWORD=${ADMIN_PASS}

WEB_PORT=8080
WEB_CONCURRENCY=2
EOF

chmod 600 .env

echo "Wrote .env (mode 600)."
echo
echo "  Bootstrap admin login:"
echo "    email:    ${ADMIN_EMAIL}"
echo "    password: ${ADMIN_PASS}"
echo
echo "Next:  docker compose up -d --build   then open http://localhost:8080"
