#!/usr/bin/env bash
# Generate a ready-to-run .env with a strong database password.
#
# Note: this app has no login. It is open by design — front it with your own
# auth / reverse proxy / VPN for anything beyond local lab use.
set -euo pipefail
cd "$(dirname "$0")/.."

if [ -f .env ]; then
  echo ".env already exists — refusing to overwrite. Delete it first to regenerate."
  exit 0
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl is required to generate secrets." >&2
  exit 1
fi

cat > .env <<INNER
# Generated by scripts/init-env.sh — keep this file secret.
POSTGRES_USER=detonate
POSTGRES_PASSWORD=$(openssl rand -hex 24)
POSTGRES_DB=detonate

WEB_PORT=8080

# Analysis engine. 'static' extracts strings from the submitted file and matches
# them against signature rules; it needs RETAIN_BYTES=true to have anything to read.
# 'simulated' reads nothing and fabricates a report from the hash (demo only).
SANDBOX_CONNECTOR=static
RETAIN_BYTES=true
MAX_UPLOAD_BYTES=104857600
ANALYSIS_CONCURRENCY=2

RATE_MAX_REQUESTS=120
SUBMIT_MAX_REQUESTS=12
INNER

chmod 600 .env

echo "Wrote .env (mode 600) with a generated database password."
echo
echo "  This app has no login — do not expose it without your own auth in front."
echo
echo "Next:  make up    then open http://localhost:8080"
